from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from datetime import datetime


class FlightReadinessReportGenerator:
    """
    Generates a Flight Readiness PDF report
    for Category II fighter / attack aircraft.
    """

    def generate(
        self,
        output_path,
        readiness,
        llm_output,
        confidence_score,
        dataset_name="Uploaded CSV"
    ):
        styles = getSampleStyleSheet()
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        story = []

        # ---------- Title ----------
        story.append(Paragraph(
            "<b>Aircraft Flight Readiness Report</b>",
            styles["Title"]
        ))
        story.append(Spacer(1, 12))

        # ---------- Metadata ----------
        meta_table = Table([
            ["Aircraft Category", "Category II – Fighter / Attack Aircraft"],
            ["Dataset", dataset_name],
            ["Generated On", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Assessment Status", readiness["status"]],
            ["Confidence Score", f'{confidence_score}%']
        ])

        meta_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]))

        story.append(meta_table)
        story.append(Spacer(1, 16))

        # ---------- Summary ----------
        story.append(Paragraph("<b>Assessment Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph(readiness["summary"], styles["Normal"]))
        story.append(Spacer(1, 12))

        # ---------- Explanation ----------
        story.append(Paragraph("<b>Analytical Explanation</b>", styles["Heading2"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph(llm_output["Explanation"], styles["Normal"]))
        story.append(Spacer(1, 12))

        # ---------- Issues ----------
        story.append(Paragraph("<b>Identified Issues</b>", styles["Heading2"]))
        story.append(Spacer(1, 6))

        if llm_output["Defects"]:
            for issue in llm_output["Defects"]:
                story.append(Paragraph(f"- {issue}", styles["Normal"]))
        else:
            story.append(Paragraph("No critical issues identified.", styles["Normal"]))

        story.append(Spacer(1, 12))

        # ---------- Recommendations ----------
        story.append(Paragraph("<b>Recommendations</b>", styles["Heading2"]))
        story.append(Spacer(1, 6))

        for rec in llm_output["Recommendations"]:
            story.append(Paragraph(f"- {rec}", styles["Normal"]))

        story.append(Spacer(1, 16))

        # ---------- Footer ----------
        story.append(Paragraph(
            "<i>This report is generated by an automated decision-support "
            "system. Final flight clearance remains the responsibility "
            "of authorized flight safety personnel.</i>",
            styles["Italic"]
        ))

        doc.build(story)
