class PromptBuilder:
    """
    Builds a structured prompt for the LLM explanation layer
    using analytics and decision-engine outputs.
    """

    def build_prompt(
        self,
        readiness_output,
        root_causes,
        analytics_summary,
        maintenance_text=""
    ):
        status = readiness_output.get("status", "UNKNOWN")
        issues = readiness_output.get("issues", [])
        summary = readiness_output.get("summary", "")

        # Recommendations are generated by LLM,
        # not required from decision engine
        issues_text = (
            "\n".join(f"- {issue}" for issue in issues)
            if issues
            else "No critical issues detected."
        )

        root_causes_text = (
            ", ".join(root_causes)
            if root_causes
            else "No specific root causes identified."
        )

        prompt = f"""
AIRCRAFT FLIGHT READINESS ASSESSMENT

Final Status:
{status}

Summary:
{summary}

Identified Issues:
{issues_text}

Root Cause Analysis:
{root_causes_text}

Maintenance / Context (if any):
{maintenance_text}

Task:
Explain the flight readiness decision in clear technical terms and
provide actionable recommendations suitable for fighter aircraft
maintenance and operations.
"""

        return prompt.strip()
